# Generated by Django 4.0.6 on 2023-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='veune_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='veune_phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='veune_web',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
    ]
